<?php
//this is Maintenance model

class Maintenance
{
    var $maintenance_id;
    var $machine_name;
    var $machine_status;
	var $check_date;
	var $checker;
	var $remarks;
    
    function __construct()
    {
        $this->maintenance_id = 00000000;
        $this->machine_name = "@mname";
        $this->machine_status = "@mstat";
        $this->check_date = "@cdate";
		$this->checker = "@cname";
		$this->remarks = "@remarks";
    }
	//maintenance_id -> autogenerated in the database 

    //machine_name
    function setMachineName($machine_name)
    {
        $this->machine_name = $machine_name;
    }
    function getMachineName()
    {
       return $this->machine_name; 
    }
	
	//machine_status
	function setMachineStatus($machine_status)
    {
        $this->machine_status = $machine_status;
    }
    function getMachineStatus()
    {
       return $this->machine_status; 
    }
	
	//check_date
	function setCheckDate($check_date)
    {
        $this->check_date = $check_date;
    }
    function getCheckDate()
    {
       return $this->check_date; 
    }

	//checker
	function setChecker($checker)
    {
        $this->checker = $checker;
    }
    function getChecker()
    {
       return $this->checker; 
    }
	
	//remarks
	function setRemarks($remarks)
    {
        $this->remarks = $remarks;
    }
    function getRemarks()
    {
       return $this->remarks; 
    }


}

?>